### ISSUE TITLE
what about merging all experts into one

### ISSUE THREAD

**Issue by dawson-chen** [Shwai-He/MEO#1]
In your paper, MEO is significantly better than vanilla MoE. 
So, i'm wondering what kind of performance it will lead to if we just merge all expert into one? dense model actually
Have u experimented on that or maybe give some insights

**Comment by Shwai-He** [comment]
Hi, I believe that merging all experts may not be the optimal approach. As indicated in Table 1 of our paper, selecting all experts leads to suboptimal performance. Feel free to raise more questions, and you can also contact the authors via email.

**Comment by kpup1710** [comment]
> Hi, I believe that merging all experts may not be the optimal approach. As indicated in Table 1 of our paper, selecting all experts leads to suboptimal performance. Feel free to raise more questions, and you can also contact the authors via email.

Hi, have you read this paper recently uploaded to to https://arxiv.org/abs/2405.03133. They propose to merge all experts.
