### ISSUE TITLE
Possibility of Information leakage during causal language modelling task

### ISSUE THREAD

**Issue by kpup1710** [Shwai-He/MEO#2]
Hi, thanks for your amazing work. I am wondering that during the training of causal language modelling task, the paper says that you perform token attn and then sequence level routing which take the mean of the batch w.r.t the sequence dim and then perform routing. Will this cause information leakage since by taking average of all token and then calculating score, you let the past tokens interact with the future tokens.

**Comment by Shwai-He** [comment]
Hi, thanks for the question. I believe formulation (6) provides a detailed explanation of token attention, which is performed only within individual tokens.

**Comment by kpup1710** [comment]
I dont really understand the purpose of eq (6) since it only performs transformation on token level. After that the authors still take the mean of the input sequence along the sequence dim which can cause information leakage as indicated in section 2.2 of this paper https://arxiv.org/pdf/2405.03133 .


![1000002508](https://github.com/Shwai-He/MEO/assets/71597672/4289ec19-f8b2-46fc-ad43-84167d399ebd)
