### ISSUE TITLE
regarding training

### ISSUE THREAD

**Issue by sorobedio** [Shwai-He/MEO#3]
If I understand correctly, you trained a separate BERT-base-uncased model as a mixture of experts for each dataset, such as having one model for SST-2 and another for RTE. This means that the experts in the model trained on SST-2 are different from those trained on RTE. In other words, you trained nine mixture of experts models and then merged them into a single expert to obtain nine different models for the GLUE tasks.
is that right?

**Comment by Shwai-He** [comment]
Sorry for the late response. You are right. These models are fine-tuned on specific datasets.
